window.esdocSearchIndex = [
  [
    "cordova-plugin-admob-free/admob~ad_size",
    "variable/index.html#static-variable-AD_SIZE",
    "<span>AD_SIZE</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "variable"
  ],
  [
    "cordova-plugin-admob-free/admob~banner",
    "class/js/banner.js~Banner.html",
    "<span>Banner</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "class"
  ],
  [
    "cordova-plugin-admob-free/admob~interstitial",
    "class/js/interstitial.js~Interstitial.html",
    "<span>Interstitial</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "class"
  ],
  [
    "cordova-plugin-admob-free/admob~rewardvideo",
    "class/js/reward-video.js~RewardVideo.html",
    "<span>RewardVideo</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "class"
  ],
  [
    "cordova-plugin-admob-free/admob~banner",
    "variable/index.html#static-variable-banner",
    "<span>banner</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "variable"
  ],
  [
    "cordova-plugin-admob-free/admob~createbannerview",
    "function/index.html#static-function-createBannerView",
    "<span>createBannerView</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "function"
  ],
  [
    "cordova-plugin-admob-free/admob~createinterstitialview",
    "function/index.html#static-function-createInterstitialView",
    "<span>createInterstitialView</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "function"
  ],
  [
    "cordova-plugin-admob-free/admob~destroybannerview",
    "function/index.html#static-function-destroyBannerView",
    "<span>destroyBannerView</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "function"
  ],
  [
    "cordova-plugin-admob-free/admob~interstitial",
    "variable/index.html#static-variable-interstitial",
    "<span>interstitial</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "variable"
  ],
  [
    "cordova-plugin-admob-free/admob~prepareinterstitial",
    "function/index.html#static-function-prepareInterstitial",
    "<span>prepareInterstitial</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "function"
  ],
  [
    "cordova-plugin-admob-free/admob~requestinterstitialad",
    "function/index.html#static-function-requestInterstitialAd",
    "<span>requestInterstitialAd</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "function"
  ],
  [
    "cordova-plugin-admob-free/admob~rewardvideo",
    "variable/index.html#static-variable-rewardvideo",
    "<span>rewardvideo</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "variable"
  ],
  [
    "cordova-plugin-admob-free/admob~setoptions",
    "function/index.html#static-function-setOptions",
    "<span>setOptions</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "function"
  ],
  [
    "cordova-plugin-admob-free/admob~showad",
    "function/index.html#static-function-showAd",
    "<span>showAd</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "function"
  ],
  [
    "cordova-plugin-admob-free/admob~showinterstitial",
    "function/index.html#static-function-showInterstitial",
    "<span>showInterstitial</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "function"
  ],
  [
    "cordova-plugin-admob-free/admob~showinterstitialad",
    "function/index.html#static-function-showInterstitialAd",
    "<span>showInterstitialAd</span> <span class=\"search-result-import-path\">cordova-plugin-admob-free/admob</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "js/admob.js",
    "file/js/admob.js.html",
    "js/admob.js",
    "file"
  ],
  [
    "js/admob.js~cordova-admob-mediation",
    "https://github.com/rehy/cordova-admob-mediation",
    "js/admob.js~cordova-admob-mediation",
    "external"
  ],
  [
    "js/banner.js",
    "file/js/banner.js.html",
    "js/banner.js",
    "file"
  ],
  [
    "js/banner.js~banner_size",
    "typedef/index.html#static-typedef-BANNER_SIZE",
    "js/banner.js~BANNER_SIZE",
    "typedef"
  ],
  [
    "js/banner.js~banner#config",
    "class/js/banner.js~Banner.html#instance-method-config",
    "js/banner.js~Banner#config",
    "method"
  ],
  [
    "js/banner.js~banner#constructor",
    "class/js/banner.js~Banner.html#instance-constructor-constructor",
    "js/banner.js~Banner#constructor",
    "method"
  ],
  [
    "js/banner.js~banner#hide",
    "class/js/banner.js~Banner.html#instance-method-hide",
    "js/banner.js~Banner#hide",
    "method"
  ],
  [
    "js/banner.js~banner#prepare",
    "class/js/banner.js~Banner.html#instance-method-prepare",
    "js/banner.js~Banner#prepare",
    "method"
  ],
  [
    "js/banner.js~banner#remove",
    "class/js/banner.js~Banner.html#instance-method-remove",
    "js/banner.js~Banner#remove",
    "method"
  ],
  [
    "js/banner.js~banner#show",
    "class/js/banner.js~Banner.html#instance-method-show",
    "js/banner.js~Banner#show",
    "method"
  ],
  [
    "js/banner.js~banner.events",
    "class/js/banner.js~Banner.html#static-member-events",
    "js/banner.js~Banner.events",
    "member"
  ],
  [
    "js/banner.js~banner.sizes",
    "class/js/banner.js~Banner.html#static-member-sizes",
    "js/banner.js~Banner.sizes",
    "member"
  ],
  [
    "js/banner.js~bannerconfig",
    "typedef/index.html#static-typedef-BannerConfig",
    "js/banner.js~BannerConfig",
    "typedef"
  ],
  [
    "js/interstitial.js",
    "file/js/interstitial.js.html",
    "js/interstitial.js",
    "file"
  ],
  [
    "js/interstitial.js~interstitial#config",
    "class/js/interstitial.js~Interstitial.html#instance-method-config",
    "js/interstitial.js~Interstitial#config",
    "method"
  ],
  [
    "js/interstitial.js~interstitial#constructor",
    "class/js/interstitial.js~Interstitial.html#instance-constructor-constructor",
    "js/interstitial.js~Interstitial#constructor",
    "method"
  ],
  [
    "js/interstitial.js~interstitial#prepare",
    "class/js/interstitial.js~Interstitial.html#instance-method-prepare",
    "js/interstitial.js~Interstitial#prepare",
    "method"
  ],
  [
    "js/interstitial.js~interstitial#show",
    "class/js/interstitial.js~Interstitial.html#instance-method-show",
    "js/interstitial.js~Interstitial#show",
    "method"
  ],
  [
    "js/interstitial.js~interstitial.events",
    "class/js/interstitial.js~Interstitial.html#static-member-events",
    "js/interstitial.js~Interstitial.events",
    "member"
  ],
  [
    "js/interstitial.js~interstitialconfig",
    "typedef/index.html#static-typedef-InterstitialConfig",
    "js/interstitial.js~InterstitialConfig",
    "typedef"
  ],
  [
    "js/reward-video.js",
    "file/js/reward-video.js.html",
    "js/reward-video.js",
    "file"
  ],
  [
    "js/reward-video.js~rewardvideo#config",
    "class/js/reward-video.js~RewardVideo.html#instance-method-config",
    "js/reward-video.js~RewardVideo#config",
    "method"
  ],
  [
    "js/reward-video.js~rewardvideo#constructor",
    "class/js/reward-video.js~RewardVideo.html#instance-constructor-constructor",
    "js/reward-video.js~RewardVideo#constructor",
    "method"
  ],
  [
    "js/reward-video.js~rewardvideo#prepare",
    "class/js/reward-video.js~RewardVideo.html#instance-method-prepare",
    "js/reward-video.js~RewardVideo#prepare",
    "method"
  ],
  [
    "js/reward-video.js~rewardvideo#show",
    "class/js/reward-video.js~RewardVideo.html#instance-method-show",
    "js/reward-video.js~RewardVideo#show",
    "method"
  ],
  [
    "js/reward-video.js~rewardvideo.events",
    "class/js/reward-video.js~RewardVideo.html#static-member-events",
    "js/reward-video.js~RewardVideo.events",
    "member"
  ],
  [
    "js/reward-video.js~rewardvideoconfig",
    "typedef/index.html#static-typedef-RewardVideoConfig",
    "js/reward-video.js~RewardVideoConfig",
    "typedef"
  ],
  [
    "js/utils.js",
    "file/js/utils.js.html",
    "js/utils.js",
    "file"
  ]
]